BEGIN;

CREATE TABLE IF NOT EXISTS todo_users (
id SERIAL PRIMARY KEY,
username VARCHAR UNIQUE NOT NULL,
email VARCHAR UNIQUE NOT NULL,
password VARCHAR);
 

CREATE TABLE IF NOT EXISTS todos (
id SERIAL PRIMARY KEY,
todo TEXT NOT NULL,
is_done BOOLEAN DEFAULT FALSE,
user_id INTEGER NOT NULL,
FOREIGN KEY (user_id) REFERENCES todo_users (id));

COMMIT;
